positional_encoding:
  num_positional_encoding_functions: 10
  num_directional_encoding_functions: 4

rendering_variables:
  depth_samples_per_ray: 50
  samples_per_model_forward_pass: 10000

training_variables:
  learning_rate: .0005
  num_iters: 19901
  rescale_factor: 2

display_variables:
  display_every: 100